version: '3.1'

services:
  mongodb:
    image: mongo:latest
    container_name: poc-soluevo
    ports:
      - "27017:27017"
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: root
    restart: always
